/* Generated by wayland-scanner 1.25.0 */

#ifndef EXT_BACKGROUND_EFFECT_V1_SERVER_PROTOCOL_H
#define EXT_BACKGROUND_EFFECT_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;
struct wl_region;
struct wl_surface;
struct ext_background_effect_manager_v1;
struct ext_background_effect_surface_v1;

#ifndef EXT_BACKGROUND_EFFECT_MANAGER_V1_INTERFACE
#define EXT_BACKGROUND_EFFECT_MANAGER_V1_INTERFACE
extern const struct wl_interface ext_background_effect_manager_v1_interface;
#endif
#ifndef EXT_BACKGROUND_EFFECT_SURFACE_V1_INTERFACE
#define EXT_BACKGROUND_EFFECT_SURFACE_V1_INTERFACE
extern const struct wl_interface ext_background_effect_surface_v1_interface;
#endif

#ifndef EXT_BACKGROUND_EFFECT_MANAGER_V1_ERROR_ENUM
#define EXT_BACKGROUND_EFFECT_MANAGER_V1_ERROR_ENUM
enum ext_background_effect_manager_v1_error {
	EXT_BACKGROUND_EFFECT_MANAGER_V1_ERROR_BACKGROUND_EFFECT_EXISTS = 0,
};
#endif /* EXT_BACKGROUND_EFFECT_MANAGER_V1_ERROR_ENUM */

#ifndef EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITY_ENUM
#define EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITY_ENUM
enum ext_background_effect_manager_v1_capability {
	EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITY_BLUR = 1,
};
#endif /* EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITY_ENUM */

struct ext_background_effect_manager_v1_interface {
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	void (*get_background_effect)(struct wl_client *client,
				      struct wl_resource *resource,
				      uint32_t id,
				      struct wl_resource *surface);
};

#define EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITIES 0

#define EXT_BACKGROUND_EFFECT_MANAGER_V1_DESTROY_SINCE_VERSION 1
#define EXT_BACKGROUND_EFFECT_MANAGER_V1_GET_BACKGROUND_EFFECT_SINCE_VERSION 1
#define EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITIES_SINCE_VERSION 1

static inline void
ext_background_effect_manager_v1_send_capabilities(struct wl_resource *resource_, uint32_t flags)
{
	wl_resource_post_event(resource_, EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITIES, flags);
}

#ifndef EXT_BACKGROUND_EFFECT_SURFACE_V1_ERROR_ENUM
#define EXT_BACKGROUND_EFFECT_SURFACE_V1_ERROR_ENUM
enum ext_background_effect_surface_v1_error {
	EXT_BACKGROUND_EFFECT_SURFACE_V1_ERROR_SURFACE_DESTROYED = 0,
};
#endif /* EXT_BACKGROUND_EFFECT_SURFACE_V1_ERROR_ENUM */

struct ext_background_effect_surface_v1_interface {
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	void (*set_blur_region)(struct wl_client *client,
				struct wl_resource *resource,
				struct wl_resource *region);
};

#define EXT_BACKGROUND_EFFECT_SURFACE_V1_DESTROY_SINCE_VERSION 1
#define EXT_BACKGROUND_EFFECT_SURFACE_V1_SET_BLUR_REGION_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
