/* Generated by wayland-scanner 1.25.0 */

#ifndef WLR_LAYER_SHELL_UNSTABLE_V1_SERVER_PROTOCOL_H
#define WLR_LAYER_SHELL_UNSTABLE_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_wlr_layer_shell_unstable_v1 The wlr_layer_shell_unstable_v1 protocol
 * @section page_ifaces_wlr_layer_shell_unstable_v1 Interfaces
 * - @subpage page_iface_zwlr_layer_shell_v1 - 
 * - @subpage page_iface_zwlr_layer_surface_v1 - 
 */
struct wl_output;
struct wl_surface;
struct xdg_popup;
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;

#ifndef ZWLR_LAYER_SHELL_V1_INTERFACE
#define ZWLR_LAYER_SHELL_V1_INTERFACE
/**
 * @page page_iface_zwlr_layer_shell_v1 zwlr_layer_shell_v1
 * @section page_iface_zwlr_layer_shell_v1_api API
 * See @ref iface_zwlr_layer_shell_v1.
 */
/**
 * @defgroup iface_zwlr_layer_shell_v1 The zwlr_layer_shell_v1 interface
 */
extern const struct wl_interface zwlr_layer_shell_v1_interface;
#endif
#ifndef ZWLR_LAYER_SURFACE_V1_INTERFACE
#define ZWLR_LAYER_SURFACE_V1_INTERFACE
/**
 * @page page_iface_zwlr_layer_surface_v1 zwlr_layer_surface_v1
 * @section page_iface_zwlr_layer_surface_v1_api API
 * See @ref iface_zwlr_layer_surface_v1.
 */
/**
 * @defgroup iface_zwlr_layer_surface_v1 The zwlr_layer_surface_v1 interface
 */
extern const struct wl_interface zwlr_layer_surface_v1_interface;
#endif

#ifndef ZWLR_LAYER_SHELL_V1_ERROR_ENUM
#define ZWLR_LAYER_SHELL_V1_ERROR_ENUM
enum zwlr_layer_shell_v1_error {
	ZWLR_LAYER_SHELL_V1_ERROR_ROLE = 0,
	ZWLR_LAYER_SHELL_V1_ERROR_INVALID_LAYER = 1,
	ZWLR_LAYER_SHELL_V1_ERROR_ALREADY_CONSTRUCTED = 2,
};
#endif /* ZWLR_LAYER_SHELL_V1_ERROR_ENUM */

#ifndef ZWLR_LAYER_SHELL_V1_ERROR_ENUM_IS_VALID
#define ZWLR_LAYER_SHELL_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_zwlr_layer_shell_v1
 * Validate a zwlr_layer_shell_v1 error value.
 *
 * @return true on success, false on error.
 * @ref zwlr_layer_shell_v1_error
 */
static inline bool
zwlr_layer_shell_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWLR_LAYER_SHELL_V1_ERROR_ROLE:
		return version >= 1;
	case ZWLR_LAYER_SHELL_V1_ERROR_INVALID_LAYER:
		return version >= 1;
	case ZWLR_LAYER_SHELL_V1_ERROR_ALREADY_CONSTRUCTED:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWLR_LAYER_SHELL_V1_ERROR_ENUM_IS_VALID */

#ifndef ZWLR_LAYER_SHELL_V1_LAYER_ENUM
#define ZWLR_LAYER_SHELL_V1_LAYER_ENUM
enum zwlr_layer_shell_v1_layer {
	ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND = 0,
	ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM = 1,
	ZWLR_LAYER_SHELL_V1_LAYER_TOP = 2,
	ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY = 3,
};
#endif /* ZWLR_LAYER_SHELL_V1_LAYER_ENUM */

#ifndef ZWLR_LAYER_SHELL_V1_LAYER_ENUM_IS_VALID
#define ZWLR_LAYER_SHELL_V1_LAYER_ENUM_IS_VALID
/**
 * @ingroup iface_zwlr_layer_shell_v1
 * Validate a zwlr_layer_shell_v1 layer value.
 *
 * @return true on success, false on error.
 * @ref zwlr_layer_shell_v1_layer
 */
static inline bool
zwlr_layer_shell_v1_layer_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND:
		return version >= 1;
	case ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM:
		return version >= 1;
	case ZWLR_LAYER_SHELL_V1_LAYER_TOP:
		return version >= 1;
	case ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWLR_LAYER_SHELL_V1_LAYER_ENUM_IS_VALID */

/**
 * @ingroup iface_zwlr_layer_shell_v1
 * @struct zwlr_layer_shell_v1_interface
 */
struct zwlr_layer_shell_v1_interface {
	/**
	 */
	void (*get_layer_surface)(struct wl_client *client,
				  struct wl_resource *resource,
				  uint32_t id,
				  struct wl_resource *surface,
				  struct wl_resource *output,
				  uint32_t layer,
				  const char *namespace_);
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_zwlr_layer_shell_v1
 */
#define ZWLR_LAYER_SHELL_V1_GET_LAYER_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_shell_v1
 */
#define ZWLR_LAYER_SHELL_V1_DESTROY_SINCE_VERSION 1

#ifndef ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM
#define ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM
enum zwlr_layer_surface_v1_keyboard_interactivity {
	ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE = 0,
	ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_EXCLUSIVE = 1,
};
#endif /* ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM */

#ifndef ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM_IS_VALID
#define ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM_IS_VALID
/**
 * @ingroup iface_zwlr_layer_surface_v1
 * Validate a zwlr_layer_surface_v1 keyboard_interactivity value.
 *
 * @return true on success, false on error.
 * @ref zwlr_layer_surface_v1_keyboard_interactivity
 */
static inline bool
zwlr_layer_surface_v1_keyboard_interactivity_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE:
		return version >= 1;
	case ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_EXCLUSIVE:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM_IS_VALID */

#ifndef ZWLR_LAYER_SURFACE_V1_ERROR_ENUM
#define ZWLR_LAYER_SURFACE_V1_ERROR_ENUM
enum zwlr_layer_surface_v1_error {
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SURFACE_STATE = 0,
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SIZE = 1,
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_ANCHOR = 2,
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_KEYBOARD_INTERACTIVITY = 3,
};
#endif /* ZWLR_LAYER_SURFACE_V1_ERROR_ENUM */

#ifndef ZWLR_LAYER_SURFACE_V1_ERROR_ENUM_IS_VALID
#define ZWLR_LAYER_SURFACE_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_zwlr_layer_surface_v1
 * Validate a zwlr_layer_surface_v1 error value.
 *
 * @return true on success, false on error.
 * @ref zwlr_layer_surface_v1_error
 */
static inline bool
zwlr_layer_surface_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SURFACE_STATE:
		return version >= 1;
	case ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SIZE:
		return version >= 1;
	case ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_ANCHOR:
		return version >= 1;
	case ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_KEYBOARD_INTERACTIVITY:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWLR_LAYER_SURFACE_V1_ERROR_ENUM_IS_VALID */

#ifndef ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM
#define ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM
enum zwlr_layer_surface_v1_anchor {
	ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP = 1,
	ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM = 2,
	ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT = 4,
	ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT = 8,
};
#endif /* ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM */

#ifndef ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM_IS_VALID
#define ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM_IS_VALID
/**
 * @ingroup iface_zwlr_layer_surface_v1
 * Validate a zwlr_layer_surface_v1 anchor value.
 *
 * @return true on success, false on error.
 * @ref zwlr_layer_surface_v1_anchor
 */
static inline bool
zwlr_layer_surface_v1_anchor_is_valid(uint32_t value, uint32_t version) {
	uint32_t valid = 0;
	if (version >= 1)
		valid |= ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP;
	if (version >= 1)
		valid |= ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
	if (version >= 1)
		valid |= ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT;
	if (version >= 1)
		valid |= ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
	return (value & ~valid) == 0;
}
#endif /* ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM_IS_VALID */

/**
 * @ingroup iface_zwlr_layer_surface_v1
 * @struct zwlr_layer_surface_v1_interface
 */
struct zwlr_layer_surface_v1_interface {
	/**
	 */
	void (*set_size)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t width,
			 uint32_t height);
	/**
	 */
	void (*set_anchor)(struct wl_client *client,
			   struct wl_resource *resource,
			   uint32_t anchor);
	/**
	 */
	void (*set_exclusive_zone)(struct wl_client *client,
				   struct wl_resource *resource,
				   int32_t zone);
	/**
	 */
	void (*set_margin)(struct wl_client *client,
			   struct wl_resource *resource,
			   int32_t top,
			   int32_t right,
			   int32_t bottom,
			   int32_t left);
	/**
	 */
	void (*set_keyboard_interactivity)(struct wl_client *client,
					   struct wl_resource *resource,
					   uint32_t keyboard_interactivity);
	/**
	 */
	void (*get_popup)(struct wl_client *client,
			  struct wl_resource *resource,
			  struct wl_resource *popup);
	/**
	 */
	void (*ack_configure)(struct wl_client *client,
			      struct wl_resource *resource,
			      uint32_t serial);
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};

#define ZWLR_LAYER_SURFACE_V1_CONFIGURE 0
#define ZWLR_LAYER_SURFACE_V1_CLOSED 1

/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_CONFIGURE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_CLOSED_SINCE_VERSION 1

/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_SIZE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_ANCHOR_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_EXCLUSIVE_ZONE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_MARGIN_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_KEYBOARD_INTERACTIVITY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_GET_POPUP_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_ACK_CONFIGURE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_zwlr_layer_surface_v1
 * Sends an configure event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwlr_layer_surface_v1_send_configure(struct wl_resource *resource_, uint32_t serial, uint32_t width, uint32_t height)
{
	wl_resource_post_event(resource_, ZWLR_LAYER_SURFACE_V1_CONFIGURE, serial, width, height);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 * Sends an closed event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwlr_layer_surface_v1_send_closed(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZWLR_LAYER_SURFACE_V1_CLOSED);
}

#ifdef  __cplusplus
}
#endif

#endif
