/* Generated by wayland-scanner 1.25.0 */

#ifndef XX_LAYER_CHROME_V1_CLIENT_PROTOCOL_H
#define XX_LAYER_CHROME_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_xx_layer_chrome_v1 The xx_layer_chrome_v1 protocol
 * @section page_ifaces_xx_layer_chrome_v1 Interfaces
 * - @subpage page_iface_xx_layer_chrome_manager_v1 - layer-shell chrome metadata factory
 * - @subpage page_iface_xx_layer_chrome_v1 - layer-shell chrome metadata
 * @section page_copyright_xx_layer_chrome_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 Flux contributors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct xx_layer_chrome_manager_v1;
struct xx_layer_chrome_v1;
struct zwlr_layer_surface_v1;

#ifndef XX_LAYER_CHROME_MANAGER_V1_INTERFACE
#define XX_LAYER_CHROME_MANAGER_V1_INTERFACE
/**
 * @page page_iface_xx_layer_chrome_manager_v1 xx_layer_chrome_manager_v1
 * @section page_iface_xx_layer_chrome_manager_v1_desc Description
 *
 * Allows clients to attach compositor-side chrome hints to layer-shell
 * surfaces (blur tint, border, style).
 * @section page_iface_xx_layer_chrome_manager_v1_api API
 * See @ref iface_xx_layer_chrome_manager_v1.
 */
/**
 * @defgroup iface_xx_layer_chrome_manager_v1 The xx_layer_chrome_manager_v1 interface
 *
 * Allows clients to attach compositor-side chrome hints to layer-shell
 * surfaces (blur tint, border, style).
 */
extern const struct wl_interface xx_layer_chrome_manager_v1_interface;
#endif
#ifndef XX_LAYER_CHROME_V1_INTERFACE
#define XX_LAYER_CHROME_V1_INTERFACE
/**
 * @page page_iface_xx_layer_chrome_v1 xx_layer_chrome_v1
 * @section page_iface_xx_layer_chrome_v1_desc Description
 *
 * Double-buffered chrome hints applied on the next wl_surface.commit of the
 * associated layer surface.
 * @section page_iface_xx_layer_chrome_v1_api API
 * See @ref iface_xx_layer_chrome_v1.
 */
/**
 * @defgroup iface_xx_layer_chrome_v1 The xx_layer_chrome_v1 interface
 *
 * Double-buffered chrome hints applied on the next wl_surface.commit of the
 * associated layer surface.
 */
extern const struct wl_interface xx_layer_chrome_v1_interface;
#endif

#ifndef XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM
#define XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM
enum xx_layer_chrome_manager_v1_error {
	/**
	 * the layer surface already has a chrome object
	 */
	XX_LAYER_CHROME_MANAGER_V1_ERROR_CHROME_EXISTS = 0,
	/**
	 * the surface is not a layer-shell surface
	 */
	XX_LAYER_CHROME_MANAGER_V1_ERROR_INVALID_ROLE = 1,
};
#endif /* XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM */

#define XX_LAYER_CHROME_MANAGER_V1_DESTROY 0
#define XX_LAYER_CHROME_MANAGER_V1_GET_LAYER_CHROME 1


/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 */
#define XX_LAYER_CHROME_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 */
#define XX_LAYER_CHROME_MANAGER_V1_GET_LAYER_CHROME_SINCE_VERSION 1

/** @ingroup iface_xx_layer_chrome_manager_v1 */
static inline void
xx_layer_chrome_manager_v1_set_user_data(struct xx_layer_chrome_manager_v1 *xx_layer_chrome_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) xx_layer_chrome_manager_v1, user_data);
}

/** @ingroup iface_xx_layer_chrome_manager_v1 */
static inline void *
xx_layer_chrome_manager_v1_get_user_data(struct xx_layer_chrome_manager_v1 *xx_layer_chrome_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) xx_layer_chrome_manager_v1);
}

static inline uint32_t
xx_layer_chrome_manager_v1_get_version(struct xx_layer_chrome_manager_v1 *xx_layer_chrome_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_manager_v1);
}

/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 */
static inline void
xx_layer_chrome_manager_v1_destroy(struct xx_layer_chrome_manager_v1 *xx_layer_chrome_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_manager_v1,
			 XX_LAYER_CHROME_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 *
 * Creates an xx_layer_chrome_v1 object for the given zwlr_layer_surface_v1.
 */
static inline struct xx_layer_chrome_v1 *
xx_layer_chrome_manager_v1_get_layer_chrome(struct xx_layer_chrome_manager_v1 *xx_layer_chrome_manager_v1, struct zwlr_layer_surface_v1 *layer_surface)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_manager_v1,
			 XX_LAYER_CHROME_MANAGER_V1_GET_LAYER_CHROME, &xx_layer_chrome_v1_interface, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_manager_v1), 0, NULL, layer_surface);

	return (struct xx_layer_chrome_v1 *) id;
}

#ifndef XX_LAYER_CHROME_V1_STYLE_ENUM
#define XX_LAYER_CHROME_V1_STYLE_ENUM
enum xx_layer_chrome_v1_style {
	XX_LAYER_CHROME_V1_STYLE_NONE = 0,
	XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL = 1,
	XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL_BORDER = 2,
};
#endif /* XX_LAYER_CHROME_V1_STYLE_ENUM */

#define XX_LAYER_CHROME_V1_DESTROY 0
#define XX_LAYER_CHROME_V1_SET_STYLE 1
#define XX_LAYER_CHROME_V1_SET_TINT 2
#define XX_LAYER_CHROME_V1_SET_BORDER 3
#define XX_LAYER_CHROME_V1_SET_BLUR_RADIUS 4
#define XX_LAYER_CHROME_V1_SET_SQUARE_BOTTOM_CORNERS 5


/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_STYLE_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_TINT_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_BORDER_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_BLUR_RADIUS_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_SQUARE_BOTTOM_CORNERS_SINCE_VERSION 1

/** @ingroup iface_xx_layer_chrome_v1 */
static inline void
xx_layer_chrome_v1_set_user_data(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) xx_layer_chrome_v1, user_data);
}

/** @ingroup iface_xx_layer_chrome_v1 */
static inline void *
xx_layer_chrome_v1_get_user_data(struct xx_layer_chrome_v1 *xx_layer_chrome_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) xx_layer_chrome_v1);
}

static inline uint32_t
xx_layer_chrome_v1_get_version(struct xx_layer_chrome_v1 *xx_layer_chrome_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_destroy(struct xx_layer_chrome_v1 *xx_layer_chrome_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_set_style(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, uint32_t style)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_SET_STYLE, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), 0, style);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_set_tint(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, uint32_t rgba)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_SET_TINT, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), 0, rgba);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_set_border(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, uint32_t rgba)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_SET_BORDER, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), 0, rgba);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_set_blur_radius(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, wl_fixed_t radius)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_SET_BLUR_RADIUS, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), 0, radius);
}

/**
 * @ingroup iface_xx_layer_chrome_v1
 */
static inline void
xx_layer_chrome_v1_set_square_bottom_corners(struct xx_layer_chrome_v1 *xx_layer_chrome_v1, uint32_t enabled)
{
	wl_proxy_marshal_flags((struct wl_proxy *) xx_layer_chrome_v1,
			 XX_LAYER_CHROME_V1_SET_SQUARE_BOTTOM_CORNERS, NULL, wl_proxy_get_version((struct wl_proxy *) xx_layer_chrome_v1), 0, enabled);
}

#ifdef  __cplusplus
}
#endif

#endif
