/* Generated by wayland-scanner 1.25.0 */

#ifndef XX_LAYER_CHROME_V1_SERVER_PROTOCOL_H
#define XX_LAYER_CHROME_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_xx_layer_chrome_v1 The xx_layer_chrome_v1 protocol
 * @section page_ifaces_xx_layer_chrome_v1 Interfaces
 * - @subpage page_iface_xx_layer_chrome_manager_v1 - layer-shell chrome metadata factory
 * - @subpage page_iface_xx_layer_chrome_v1 - layer-shell chrome metadata
 * @section page_copyright_xx_layer_chrome_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 Flux contributors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct xx_layer_chrome_manager_v1;
struct xx_layer_chrome_v1;
struct zwlr_layer_surface_v1;

#ifndef XX_LAYER_CHROME_MANAGER_V1_INTERFACE
#define XX_LAYER_CHROME_MANAGER_V1_INTERFACE
/**
 * @page page_iface_xx_layer_chrome_manager_v1 xx_layer_chrome_manager_v1
 * @section page_iface_xx_layer_chrome_manager_v1_desc Description
 *
 * Allows clients to attach compositor-side chrome hints to layer-shell
 * surfaces (blur tint, border, style).
 * @section page_iface_xx_layer_chrome_manager_v1_api API
 * See @ref iface_xx_layer_chrome_manager_v1.
 */
/**
 * @defgroup iface_xx_layer_chrome_manager_v1 The xx_layer_chrome_manager_v1 interface
 *
 * Allows clients to attach compositor-side chrome hints to layer-shell
 * surfaces (blur tint, border, style).
 */
extern const struct wl_interface xx_layer_chrome_manager_v1_interface;
#endif
#ifndef XX_LAYER_CHROME_V1_INTERFACE
#define XX_LAYER_CHROME_V1_INTERFACE
/**
 * @page page_iface_xx_layer_chrome_v1 xx_layer_chrome_v1
 * @section page_iface_xx_layer_chrome_v1_desc Description
 *
 * Double-buffered chrome hints applied on the next wl_surface.commit of the
 * associated layer surface.
 * @section page_iface_xx_layer_chrome_v1_api API
 * See @ref iface_xx_layer_chrome_v1.
 */
/**
 * @defgroup iface_xx_layer_chrome_v1 The xx_layer_chrome_v1 interface
 *
 * Double-buffered chrome hints applied on the next wl_surface.commit of the
 * associated layer surface.
 */
extern const struct wl_interface xx_layer_chrome_v1_interface;
#endif

#ifndef XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM
#define XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM
enum xx_layer_chrome_manager_v1_error {
	/**
	 * the layer surface already has a chrome object
	 */
	XX_LAYER_CHROME_MANAGER_V1_ERROR_CHROME_EXISTS = 0,
	/**
	 * the surface is not a layer-shell surface
	 */
	XX_LAYER_CHROME_MANAGER_V1_ERROR_INVALID_ROLE = 1,
};
#endif /* XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM */

#ifndef XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM_IS_VALID
#define XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 * Validate a xx_layer_chrome_manager_v1 error value.
 *
 * @return true on success, false on error.
 * @ref xx_layer_chrome_manager_v1_error
 */
static inline bool
xx_layer_chrome_manager_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case XX_LAYER_CHROME_MANAGER_V1_ERROR_CHROME_EXISTS:
		return version >= 1;
	case XX_LAYER_CHROME_MANAGER_V1_ERROR_INVALID_ROLE:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* XX_LAYER_CHROME_MANAGER_V1_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 * @struct xx_layer_chrome_manager_v1_interface
 */
struct xx_layer_chrome_manager_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * create chrome metadata for a layer surface
	 *
	 * Creates an xx_layer_chrome_v1 object for the given
	 * zwlr_layer_surface_v1.
	 */
	void (*get_layer_chrome)(struct wl_client *client,
				 struct wl_resource *resource,
				 uint32_t id,
				 struct wl_resource *layer_surface);
};


/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 */
#define XX_LAYER_CHROME_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_manager_v1
 */
#define XX_LAYER_CHROME_MANAGER_V1_GET_LAYER_CHROME_SINCE_VERSION 1

#ifndef XX_LAYER_CHROME_V1_STYLE_ENUM
#define XX_LAYER_CHROME_V1_STYLE_ENUM
enum xx_layer_chrome_v1_style {
	XX_LAYER_CHROME_V1_STYLE_NONE = 0,
	XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL = 1,
	XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL_BORDER = 2,
};
#endif /* XX_LAYER_CHROME_V1_STYLE_ENUM */

#ifndef XX_LAYER_CHROME_V1_STYLE_ENUM_IS_VALID
#define XX_LAYER_CHROME_V1_STYLE_ENUM_IS_VALID
/**
 * @ingroup iface_xx_layer_chrome_v1
 * Validate a xx_layer_chrome_v1 style value.
 *
 * @return true on success, false on error.
 * @ref xx_layer_chrome_v1_style
 */
static inline bool
xx_layer_chrome_v1_style_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case XX_LAYER_CHROME_V1_STYLE_NONE:
		return version >= 1;
	case XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL:
		return version >= 1;
	case XX_LAYER_CHROME_V1_STYLE_BLUR_PANEL_BORDER:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* XX_LAYER_CHROME_V1_STYLE_ENUM_IS_VALID */

/**
 * @ingroup iface_xx_layer_chrome_v1
 * @struct xx_layer_chrome_v1_interface
 */
struct xx_layer_chrome_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 */
	void (*set_style)(struct wl_client *client,
			  struct wl_resource *resource,
			  uint32_t style);
	/**
	 * tint color as 0xRRGGBBAA
	 *
	 * 
	 */
	void (*set_tint)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t rgba);
	/**
	 * border color as 0xRRGGBBAA
	 *
	 * 
	 */
	void (*set_border)(struct wl_client *client,
			   struct wl_resource *resource,
			   uint32_t rgba);
	/**
	 */
	void (*set_blur_radius)(struct wl_client *client,
				struct wl_resource *resource,
				wl_fixed_t radius);
	/**
	 */
	void (*set_square_bottom_corners)(struct wl_client *client,
					  struct wl_resource *resource,
					  uint32_t enabled);
};


/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_STYLE_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_TINT_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_BORDER_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_BLUR_RADIUS_SINCE_VERSION 1
/**
 * @ingroup iface_xx_layer_chrome_v1
 */
#define XX_LAYER_CHROME_V1_SET_SQUARE_BOTTOM_CORNERS_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
