if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "FluxEmbedBinary requires INPUT, OUTPUT, and SYMBOL")
endif()

file(READ "${INPUT}" _flux_bytes HEX)
string(LENGTH "${_flux_bytes}" _flux_hex_len)
math(EXPR _flux_byte_len "${_flux_hex_len} / 2")

set(_flux_out "unsigned char ${SYMBOL}[] = {")
set(_flux_col 0)
foreach(_flux_i RANGE 0 ${_flux_hex_len} 2)
  if(_flux_i EQUAL _flux_hex_len)
    break()
  endif()
  string(SUBSTRING "${_flux_bytes}" ${_flux_i} 2 _flux_byte)
  if(_flux_col EQUAL 0)
    string(APPEND _flux_out "\n  ")
  endif()
  string(APPEND _flux_out "0x${_flux_byte}, ")
  math(EXPR _flux_col "${_flux_col} + 1")
  if(_flux_col EQUAL 12)
    set(_flux_col 0)
  endif()
endforeach()
string(APPEND _flux_out "\n};\nunsigned int ${SYMBOL}_len = ${_flux_byte_len};\n")
file(WRITE "${OUTPUT}" "${_flux_out}")
